import { Track } from '@/types/music'

export const tracks: Track[] = [
  {
    title: 'Ad Astra',
    artists: ['Oscillian'],
    year: 2017,
    lyrics: false,
  },
  {
    title: 'Aftermath',
    artists: ['Volkor X'],
    year: 2020,
    lyrics: false,
  },
  {
    title: 'Aliens',
    artists: ['Wice'],
    year: 2018,
    lyrics: true,
  },
  {
    title: 'Asteroid Rain',
    artists: ['Wice'],
    year: 2018,
    lyrics: false,
  },
  {
    title: 'AWAKENING',
    artists: ['ALEX', 'TOKYO ROSE', 'F.O.O.L'],
    year: 2020,
    lyrics: false,
  },
  {
    title: 'Bad News',
    artists: ['Absolute Valentine'],
    year: 2016,
    lyrics: false,
  },
  {
    title: 'Bonzai',
    artists: ['Turbo Knight'],
    year: 2019,
    lyrics: false,
  },
  {
    title: 'Brain Of Steel',
    artists: ['Thomas Barrandon'],
    year: 2022,
    lyrics: false,
  },
  {
    title: 'Burn Inside',
    artists: ['Donbor'],
    year: 2018,
    lyrics: false,
  },
  {
    title: 'Cabin Fever in Space',
    artists: ['Waveshaper'],
    year: 2014,
    lyrics: false,
  },
  {
    title: 'Cybertronic Battle',
    artists: ['Waveshaper'],
    year: 2013,
    lyrics: false,
  },
  {
    title: 'Criminals',
    artists: ['F.O.O.L'],
    year: 2020,
    lyrics: false,
  },
  {
    title: 'Crystal Protocol',
    artists: ['Waveshaper'],
    year: 2015,
    lyrics: false,
  },
  {
    title: 'Dawn',
    artists: ['Turbo Knight'],
    year: 2017,
    lyrics: false,
  },
  {
    title: 'Data Eater',
    artists: ['Thomas Barrandon'],
    year: 2022,
    lyrics: false,
  },
  {
    title: 'Delete Soul',
    artists: ['ALEX', 'TOKYO ROSE'],
    year: 2017,
    lyrics: false,
  },
  {
    title: 'Destination Unknown',
    artists: ['Scandroid'],
    year: 2016,
    lyrics: false,
  },
  {
    title: 'Digital Contact',
    artists: ['Neon Nox'],
    year: 2020,
    lyrics: false,
  },
  {
    title: 'Doomsday Clock',
    artists: ['Thomas Barrandon'],
    year: 2018,
    lyrics: false,
  },
  {
    title: 'Drive Through the Night',
    artists: ['Cassetter'],
    year: 2019,
    lyrics: false,
  },
  {
    title: 'Electric Body, Electric Soul',
    artists: ['Robert Parker'],
    year: 2020,
    lyrics: false,
  },
  {
    title: 'Encounter',
    artists: ['F.O.O.L', 'Waveshaper'],
    year: 2023,
    lyrics: false,
  },
  {
    title: 'End of Line',
    artists: ['Daft Punk'],
    year: 2010,
    lyrics: false,
  },
  {
    title: 'End of the Night',
    artists: ['Robert Parker'],
    year: 2018,
    lyrics: true,
  },
  {
    title: 'E.P.R.O.M',
    artists: ['Waveshaper', 'Oscillian'],
    year: 2022,
    lyrics: true,
  },
  {
    title: 'Escape from Beijing',
    artists: ['Oscillian'],
    year: 2015,
    lyrics: false,
  },
  {
    title: 'Fahrenheit',
    artists: ['Neon Nox'],
    year: 2018,
    lyrics: false,
  },
  {
    title: 'Forget',
    artists: ['Donbor'],
    year: 2018,
    lyrics: false,
  },
  {
    title: 'Future Vision',
    artists: ['Waveshaper'],
    year: 2016,
    lyrics: false,
  },
  {
    title: 'Galactical',
    artists: ['Waveshaper'],
    year: 2013,
    lyrics: false,
  },
  {
    title: 'The Ghost and the Highway',
    artists: ['Droid Bishop'],
    year: 2023,
    lyrics: false,
  },
  {
    title: 'Giorgio by Moroder',
    artists: ['Daft Punk'],
    year: 2013,
    lyrics: true,
  },
  {
    title: 'GodWave Rises',
    artists: ['Volkor X'],
    year: 2017,
    lyrics: false,
  },
  {
    title: 'The Grid',
    artists: ['Daft Punk'],
    year: 2010,
    lyrics: true,
  },
  {
    title: 'Hearts',
    artists: ['Waveshaper'],
    year: 2023,
    lyrics: false,
  },
  {
    title: 'Highway',
    artists: ['F.O.O.L'],
    year: 2018,
    lyrics: false,
  },
  {
    title: 'I Drive',
    artists: ['Cliff Martinez', 'Waveshaper'],
    year: 2020,
    lyrics: false,
  },
  {
    title: 'Integrated Circutry',
    artists: ['Betamaxx'],
    year: 2015,
    lyrics: false,
  },
  {
    title: 'Last Resolve',
    artists: ['Kick Puncher'],
    year: 2020,
    lyrics: false,
  },
  {
    title: 'Lost After Dark',
    artists: ['Tonebox', 'Lucy in Disguise'],
    year: 2016,
    lyrics: false,
  },
  {
    title: 'Midnight City',
    artists: ['M83'],
    year: 2011,
    lyrics: true,
  },
  {
    title: 'Mirrorverse',
    artists: ['Turbo Knight'],
    year: 2017,
    lyrics: false,
  },
  {
    title: 'Monster in Paradise',
    artists: ['GUNSHIP'],
    year: 2023,
    lyrics: true,
  },
  {
    title: 'Neptune',
    artists: ['Wayfloe'],
    year: 2021,
    lyrics: false,
  },
  {
    title: 'Nightcall',
    artists: ['Kavinsky'],
    year: 2013,
    lyrics: true,
  },
  {
    title: 'Nuclear',
    artists: ['Lost Years'],
    year: 2012,
    lyrics: true,
  },
  {
    title: 'Overdog',
    artists: ['Le Matos'],
    year: 2013,
    lyrics: false,
  },
  {
    title: 'The Portal',
    artists: ['Volkor X'],
    year: 2015,
    lyrics: false,
  },
  {
    title: 'Prelude to War',
    artists: ['Volkor X'],
    year: 2016,
    lyrics: false,
  },
  {
    title: 'Ragnarok',
    artists: ['Wayfloe'],
    year: 2021,
    lyrics: true,
  },
  {
    title: 'Rasengan',
    artists: ['Turbo Knight'],
    year: 2018,
    lyrics: false,
  },
  {
    title: 'Red Eyes',
    artists: ['Zombie Hyperdrive'],
    year: 2016,
    lyrics: false,
  },
  {
    title: 'Red Herring - Night Ritual',
    artists: ['Kick Puncher'],
    year: 2017,
    lyrics: false,
  },
  {
    title: 'Resolution',
    artists: ['Kick Puncher'],
    year: 2015,
    lyrics: false,
  },
  {
    title: 'Restore',
    artists: ['Donbor'],
    year: 2022,
    lyrics: false,
  },
  {
    title: 'Return',
    artists: ['Donbor'],
    year: 2022,
    lyrics: false,
  },
  {
    title: 'The Return',
    artists: ['Pylot'],
    year: 2020,
    lyrics: false,
  },
  {
    title: 'She Only Exists in Screens',
    artists: ['DEADLIFE'],
    year: 2019,
    lyrics: false,
  },
  {
    title: 'Son of Flynn',
    artists: ['Daft Punk'],
    year: 2010,
    lyrics: false,
  },
  {
    title: 'The Space Hero',
    artists: ['Waveshaper'],
    year: 2016,
    lyrics: false,
  },
  {
    title: 'Star Fighter',
    artists: ['Wice'],
    year: 2017,
    lyrics: false,
  },
  {
    title: 'Stormraiders',
    artists: ['Fury Weekend'],
    year: 2019,
    lyrics: false,
  },
  {
    title: 'System Error',
    artists: ['Tonebox'],
    year: 2016,
    lyrics: false,
  },
  {
    title: 'Tech Noir',
    artists: ['GUNSHIP'],
    year: 2015,
    lyrics: true,
  },
  {
    title: 'This Means War',
    artists: ['Volkor X'],
    year: 2016,
    lyrics: false,
  },
  {
    title: 'Tunnels',
    artists: ['Neon Nox'],
    year: 2022,
    lyrics: false,
  },
  {
    title: 'Unleashed',
    artists: ['ALEX', 'TOKYO ROSE'],
    year: 2019,
    lyrics: false,
  },
  {
    title: 'Vega',
    artists: ['Thomas Barrandon'],
    year: 2023,
    lyrics: true,
  },
  {
    title: 'Visiondome',
    artists: ['Highway Superstar'],
    year: 2019,
    lyrics: false,
  },
  {
    title: 'We Are One & the Same',
    artists: ['DEADLIFE'],
    year: 2020,
    lyrics: false,
  },
  {
    title: 'Woken Furies',
    artists: ['GUNSHIP'],
    year: 2018,
    lyrics: true,
  },
  {
    title: 'Wolves',
    artists: ['Neon Nox'],
    year: 2022,
    lyrics: false,
  },
  {
    title: '3Am',
    artists: ['ALEX', 'TOKYO ROSE'],
    year: 2019,
    lyrics: false,
  },
  {
    title: '4:30',
    artists: ['Danger'],
    year: 2010,
    lyrics: false,
  },
]
